---
controller_projects:
  - name: aap.dailydemo.hashicorp
    organization: "{{ my_organization }}"
    scm_type: git
    wait: true
    scm_url: https://github.com/ericcames/aap.dailydemo.hashicorp.git
