---
- name: Provision terraform and vault
  hosts: localhost
  connection: local

  tasks:

    - name: Include the infrastructure role
      ansible.builtin.include_role:
        name: infrastructure